### ISSUE TITLE
Rewrite README.srt to markdown format

### ISSUE THREAD

**Issue by kirecek** [Vnet-as/besserberg#14]
besserberg's readme is broken at  [hub.docker](https://hub.docker.com/r/vnet/besserberg/) since dh is not supporting rst format :disappointed:

**Comment by beezz** [comment]
Another option would be to have separate README.md for dh. If I understand it correctly https://docs.docker.com/docker-hub/builds/#/understand-the-build-process. But that would require moving Dockerfile to separate directory.
